AWSTemplateFormatVersion: "2010-09-09"
Description: CodeBuild Setup for codepipeline-example
Resources:
  Build:
    Type: "AWS::CodeBuild::Project"
    Properties: 
      BadgeEnabled: False
      Description: Pull Request Build
      Name: codepipeline-example-pullrequest
      Environment: 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        PrivilegedMode: True
        Type: LINUX_CONTAINER
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !Ref PullRequestServiceRole
      Source:
        Location: https://github.com/adbrowne/codepipeline-example.git
        Type: GITHUB
      Triggers: 
        Webhook: True
  PullRequestServiceRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: CodeBuild
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: CloudWatchLogsPolicy
              Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              Resource:
              - "*"
            - Sid: CodeCommitPolicy
              Effect: Allow
              Action:
              - codecommit:GitPull
              Resource:
              - "*"
            - Sid: S3GetObjectPolicy
              Effect: Allow
              Action:
              - s3:GetObject
              - s3:GetObjectVersion
              Resource:
              - "*"
            - Sid: S3PutObjectPolicy
              Effect: Allow
              Action:
              - s3:PutObject
              Resource:
              - "*"